# fly.toml app configuration file generated for aethershelf on 2023-09-21T08:21:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aethershelf"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
